package fr.cdrochon.documentservice.model;

//TODO 140 marques à saisir
public enum MarqueVehicule {
    ABARTH, ADRIA, ALFA_ROMEO, AUDI, BMW, CADILLAC, DACIA, DUCATI, FIAT, FORD, HARLEY_DAVIDSON, HONDA,
    HYUNDAI, ISUZU, JEEP, KIA, LADA, LANCIA, MATRA, MERCEDES, OPEL, RENAULT, ROVER, SKODA, SMART, SUZUKI,
    TOYOTA, VOLKSWAGEN, VOLVO, YAMAHA
}
